# Generated by Django 6.0 on 2025-12-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_techlogo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techlogo',
            old_name='img',
            new_name='image',
        ),
    ]
