# Generated by Django 6.0 on 2025-12-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_img_techlogo_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TechLogo',
        ),
    ]
